name: Build & Test
on:
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  compile_and_test:
    name: "Compile and Test"
    strategy:
      fail-fast: false
      matrix:
        os: [mulesoft-ubuntu, mulesoft-windows]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Compile
      run: mvn --batch-mode compile
    - name: Run Tests
      run: mvn --batch-mode test
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results ${{ matrix.os }}
        path: |
          target/data-weave-test-reports/*.xml
  event_file:
    name: "Upload Event File"
    runs-on: mulesoft-ubuntu
    steps:
    - name: Upload Event File
      uses: actions/upload-artifact@v2
      with:
        name: eventFile
        path: ${{ github.event_path }}
